In [2]:
import torch

In [6]:
x = torch.rand(5,5,requires_grad=True)
y = torch.rand(5,5,requires_grad=True)
print(x,'\n',y)
z=torch.sum(x+y)
z.backward()
print(x.grad,'\n',y.grad)

tensor([[0.8619, 0.2974, 0.6771, 0.7220, 0.9335],
        [0.4639, 0.8471, 0.1546, 0.5782, 0.3647],
        [0.0807, 0.6062, 0.3392, 0.3437, 0.8434],
        [0.2202, 0.1150, 0.6621, 0.4921, 0.9410],
        [0.4854, 0.1860, 0.7733, 0.4498, 0.7449]], requires_grad=True) 
 tensor([[0.9798, 0.7187, 0.7333, 0.2223, 0.5221],
        [0.6743, 0.7181, 0.1161, 0.5691, 0.5973],
        [0.0417, 0.9348, 0.2380, 0.8879, 0.3106],
        [0.6645, 0.9932, 0.8066, 0.3070, 0.8966],
        [0.4446, 0.5427, 0.1804, 0.6351, 0.1448]], requires_grad=True)
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) 
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
