# Autograd-自动求导机制

autograd包为张量上的所有操作提供了自动求导。 它是一个在运行时定义的框架，这意味着反向传播是根据你的代码来确定如何运行，并且每次迭代可以是不同的。

### 张量(Tensor) 

In [1]:
import torch

创建一个张量x并设置 requires_grad=True 用来追踪它的计算历史

In [2]:
x=torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


对张量x进行操作并查看结果y的grad_fn属性(被自动生成) 

In [3]:
y=x+2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


对张量y进行操作

In [4]:
z=y*y*3
out=z.mean()
print(z,"\n",out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) 
 tensor(27., grad_fn=<MeanBackward0>)


.requires_grad_( ... ) 可以改变现有张量的 requires_grad属性。 如果没有指定的话，默认输入的flag是 False。

In [6]:
a=torch.randn(2,2)
a=((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b=(a*a).sum()
print(b,b.grad_fn)

False
True
tensor(3241.3933, grad_fn=<SumBackward0>) <SumBackward0 object at 0x00000178016B8828>


### 梯度

反向传播 out是一个纯量（scalar），out.backward() 等于out.backward(torch.tensor(1))。

In [7]:
out.backward()

In [8]:
print(x.grad) # 上面的张量x经过一系列操作得到结果out，然后执行out.backward()进行反向传播

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


使用autograd执行更多的操作

In [33]:
x=torch.randn(3,requires_grad=True)
y=x*2
print("init:",y)

while y.data.norm()<1000:
    y=y*2

print(y)    

init: tensor([ 1.5748, -0.1858,  2.8354], grad_fn=<MulBackward0>)
tensor([ 806.2749,  -95.1377, 1451.7339], grad_fn=<MulBackward0>)


In [35]:
print("init:",x)
print(x.grad)
gradients=torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
y.backward(gradients)
print(x)
print(x.grad)

init: tensor([ 0.7874, -0.0929,  1.4177], requires_grad=True)
None
tensor([ 0.7874, -0.0929,  1.4177], requires_grad=True)
tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


如果.requires_grad=True但是你又不希望进行autograd的计算， 那么可以将变量包裹在 with torch.no_grad()中:

In [38]:
print(x.requires_grad)
print((x **2 ).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
